name: ST-RandomBox
main: net.starly.randombox.RandomBoxMain
author: Starly Team
website: http://starly.kr/

description: RandomBox Plugin.

softdepend:
  - ST-Core

version: 1.0.2
api-version: 1.13

commands:

  random-box:
    aliases: [ randombox, 랜덤박스 ]