name: ST-RandomBox
main: net.starly.randombox.RandomBoxMain
author: Starly Team
website: http://starly.kr/

description: RandomBox Plugin.

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

commands:

  랜덤박스: